tuple = (1, 2, 3, 4, 5)
print(tuple)
don_le = (11,)
print(don_le)
new_tuple = ('meo','ga','cho')
print(new_tuple[0])
print(new_tuple[-1])
print(new_tuple[0:2])
day_tuple = (1, 5, (7, 8, 9, 10), 11, 12)
print(day_tuple[1])
print(day_tuple[-1])
print(day_tuple[2])
print(day_tuple[2][0])
for dong_vat in new_tuple:
    print(dong_vat)

print(len(new_tuple))
print(new_tuple.count("cho"))
print(new_tuple.index("cho"))
print("Hai tuple gop lai voi nhau: ",day_tuple + new_tuple)
print("Tuple lap lai voi nhau: ",day_tuple * 2)
print("vit" in day_tuple)
print(1 in day_tuple)
