f = open("thuchanh15bai.py",'r',encoding= 'utf-8')
content = f.read()
print(content)
f = open("thuchanh15bai.py",'a',encoding= 'utf-8')
for line in f:
    print(line.strip())
f.write("\nprint('Hello World')")
f.close()
f = open("main.py",'r',encoding = 'utf-8')
f.write("them dong. \n")
f.close()
f = open("haletuan.txt",'w',encoding= 'utf-8')
f.write("Ha Le Anh Tuan")
f.close()